# Tranquilpeak
# Version : 0.4.7-BETA
# Author : Thibaud Leprêtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseURL: 'https://kvaps.github.io/'
defaultContentLanguage: en-us
title: kvaps | personal blog
theme: hugo-tranquilpeak-theme
disqusShortname: kvaps
googleAnalytics: "UA-53837210-1"
paginate: 7
canonifyurls: true

algolia:
  index: "kvaps.ru"
  key: "79503842d1e3d7682f38da5eda15331b"
  appID: "DE8NJRMCBE"

permalinks:
  post: '/:year/:month/:slug/'

taxonomies:
  tag: tags
  category: categories
  archive: archives

author:
  name: Andrei Kvapil
  bio: Solutions Architect
  job: Flant
  location: Czech republic, EU
  gravatarEmail: kvapss@gmail.com

languages:
  en-us:
    contentDir: content/en
    languageCode: en-us
    languageName: English
    weight: 1

    menu:
      main:
        - weight: 1
          identifier: home
          name: Home
          pre: <i class="sidebar-button-icon fa fa-lg fa-home"></i>
          url: /
        - weight: 2
          identifier: about
          name: About
          pre: <i class="sidebar-button-icon fa fa-lg fa-question"></i>
          url: '/#about'
        #- weight: 3
        #  identifier: search
        #  name: Search
        #  pre: <i class="sidebar-button-icon fa fa-lg fa-search"></i>
        #  url: '/#search'
        #- weight: 4
        #  identifier: categories
        #  name: Categories
        #  pre: <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
        #  url: /categories
        #- weight: 5
        #  identifier: tags
        #  name: Tags
        #  pre: <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
        #  url: /tags
        - weight: 6
          identifier: archives
          name: Archives
          pre: <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
          url: /archives

      contact:
        - weight: 1
          identifier: github
          name: GitHub
          pre: <i class="sidebar-button-icon fa fa-lg fa-github"></i>
          url: 'https://github.com/kvaps'
        - weight: 2
          identifier: medium
          name: Medium
          pre: <i class="sidebar-button-icon fa fa-lg fa-medium"></i>
          url: 'https://kvaps.medium.com/'
        - weight: 3
          identifier: youtube
          name: YouTube
          pre: <i class="sidebar-button-icon fa fa-lg fa-youtube"></i>
          url: 'https://www.youtube.com/watch?v=jp2XY-9MORM&list=PLigW96d6EqkgsShnwdb0NHTLH1sAht34h'
        - weight: 4
          identifier: stackoverflow
          name: Stack Overflow
          pre: <i class="sidebar-button-icon fa fa-lg fa-stack-overflow"></i>
          url: 'https://stackoverflow.com/users/2931267/kvaps'
      links:
        - weight: 4
          identifier: projects-archive
          name: Projects Archive
          pre: <i class="sidebar-button-icon fa fa-lg fa-link"></i>
          url: '/projects-archive/'
      misc:
        - weight: 1
          identifier: telegram
          name: Telegram
          pre: <i class="sidebar-button-icon fa fa-lg fa-paper-plane"></i>
          url: 'https://t.me/kvaps'
        - weight: 2
          identifier: mail
          name: Mail
          pre: <i class="sidebar-button-icon fa fa-lg fa-envelope-o"></i>
          url: 'mailto:kvapss@gmail.com'
        - weight: 3
          identifier: rss
          name: RSS
          pre: <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
          url: /index.xml
        - weight: 4
          identifier: russian
          name: Русский
          pre: <i class="sidebar-button-icon fa fa-lg fa-language"></i>
          url: /ru/

  ru:
    contentDir: content/ru
    languageCode: ru
    languageName: Russian
    title: kvaps | личный блог
    dateFormat: "2 January 2006"
    weight: 2
    menu:
      main:
        - weight: 1
          identifier: home
          name: Главная
          pre: <i class="sidebar-button-icon fa fa-lg fa-home"></i>
          url: /
        - weight: 2
          identifier: about
          name: Об авторе
          pre: <i class="sidebar-button-icon fa fa-lg fa-question"></i>
          url: '/#about'
        #- weight: 3
        #  identifier: search
        #  name: Поиск
        #  pre: <i class="sidebar-button-icon fa fa-lg fa-search"></i>
        #  url: '/#search'
        #- weight: 4
        #  identifier: categories
        #  name: Категории
        #  pre: <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
        #  url: /categories
        #- weight: 5
        #  identifier: tags
        #  name: Тэги
        #  pre: <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
        #  url: /tags
        - weight: 6
          identifier: archives
          name: Архив
          pre: <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
          url: /archives

      contact:
        - weight: 1
          identifier: github
          name: GitHub
          pre: <i class="sidebar-button-icon fa fa-lg fa-github"></i>
          url: 'https://github.com/kvaps'
        - weight: 2
          identifier: habra
          name: Habr
          pre: <i class="sidebar-button-icon fa fa-lg fa-h-square"></i>
          url: 'https://habr.com/users/kvaps/'
        - weight: 3
          identifier: youtube
          name: YouTube
          pre: <i class="sidebar-button-icon fa fa-lg fa-youtube"></i>
          url: 'https://www.youtube.com/watch?v=jp2XY-9MORM&list=PLigW96d6EqkhiQ8a8R0q29NoPfn3jSw__'
      links:
        - weight: 4
          identifier: projects-archive
          name: Архив проектов
          pre: <i class="sidebar-button-icon fa fa-lg fa-link"></i>
          url: '/projects-archive/'
        - weight: 5
          identifier: mahjong
          name: Риичи Маджонг
          pre: <i class="sidebar-button-icon fa fa-lg fa-book"></i>
          url: '/riichi-mahjong/'
      misc:
        - weight: 1
          identifier: telegram
          name: Telegram
          pre: <i class="sidebar-button-icon fa fa-lg fa-paper-plane"></i>
          url: 'https://t.me/kvaps'
        - weight: 2
          identifier: mail
          name: Mail
          pre: <i class="sidebar-button-icon fa fa-lg fa-envelope-o"></i>
          url: 'mailto:kvapss@gmail.com'
        - weight: 3
          identifier: rss
          name: RSS
          pre: <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
          url: /index.xml
        - weight: 4
          identifier: english
          name: English
          pre: <i class="sidebar-button-icon fa fa-lg fa-language"></i>
          url: ../

params:
  #keywords: ["development", "next-gen"]
  syntaxHighlighter: highlight.js
  clearReading: false
  hierarchicalCategories: true
  #description: Hugo tranquilpeak theme demo
  sidebarBehavior: 2
  coverImage: images/cover.jpg
  imageGallery: true
  thumbnailImage: true
  thumbnailImagePosition: bottom
  autoThumbnailImage: true
  favicon: "/favicon.ico"
  #swapPaginator: true
  customCSS:
  - href: "../css/style.css"
  #customJS:
  #- src: "js/myscript.js"
  sharingOptions:
    - name: Facebook
      icon: fa-facebook-official
      url: 'https://www.facebook.com/sharer/sharer.php?u=%s'
    - name: Twitter
      icon: fa-twitter
      url: 'https://twitter.com/intent/tweet?text=%s'
    - name: Google+
      icon: fa-google-plus
      url: 'https://plus.google.com/share?url=%s'
  header:
    rightLink:
      class: ''
      icon: ''
      url: '/#about'
  sidebar:
    profile:
      url: "/#about"
  footer:
    copyright: "<a href=\"https://github.com/kvaps\">kvaps</a>"
